# TCL File Generated by Component Editor 16.1
# Thu Sep 14 13:18:24 MSK 2017
# DO NOT MODIFY


# 
# LT24_controller "LT24_controller" v1.0
#  2017.09.14.13:18:24
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module LT24_controller
# 
set_module_property DESCRIPTION ""
set_module_property NAME LT24_controller
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "My Group"
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME LT24_controller
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL lt24_ctrl
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file LT24_ctrl.sv SYSTEM_VERILOG PATH LT24_ctrl.sv TOP_LEVEL_FILE
add_fileset_file fifo.v VERILOG PATH fifo.v


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point ctrl
# 
add_interface ctrl avalon end
set_interface_property ctrl addressUnits WORDS
set_interface_property ctrl associatedClock clock
set_interface_property ctrl associatedReset reset
set_interface_property ctrl bitsPerSymbol 8
set_interface_property ctrl burstOnBurstBoundariesOnly false
set_interface_property ctrl burstcountUnits WORDS
set_interface_property ctrl explicitAddressSpan 0
set_interface_property ctrl holdTime 0
set_interface_property ctrl linewrapBursts false
set_interface_property ctrl maximumPendingReadTransactions 0
set_interface_property ctrl maximumPendingWriteTransactions 0
set_interface_property ctrl readLatency 0
set_interface_property ctrl readWaitTime 1
set_interface_property ctrl setupTime 0
set_interface_property ctrl timingUnits Cycles
set_interface_property ctrl writeWaitTime 0
set_interface_property ctrl ENABLED true
set_interface_property ctrl EXPORT_OF ""
set_interface_property ctrl PORT_NAME_MAP ""
set_interface_property ctrl CMSIS_SVD_VARIABLES ""
set_interface_property ctrl SVD_ADDRESS_GROUP ""

add_interface_port ctrl ctrl_write write Input 1
add_interface_port ctrl ctrl_writedata writedata Input 32
add_interface_port ctrl ctrl_read read Input 1
add_interface_port ctrl ctrl_readdata readdata Output 32
add_interface_port ctrl ctrl_address address Input 3
add_interface_port ctrl ctrl_waitrequest waitrequest Output 1
set_interface_assignment ctrl embeddedsw.configuration.isFlash 0
set_interface_assignment ctrl embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment ctrl embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment ctrl embeddedsw.configuration.isPrintableDevice 0


# 
# connection point lt24_cs_n
# 
add_interface lt24_cs_n conduit end
set_interface_property lt24_cs_n associatedClock clock
set_interface_property lt24_cs_n associatedReset ""
set_interface_property lt24_cs_n ENABLED true
set_interface_property lt24_cs_n EXPORT_OF ""
set_interface_property lt24_cs_n PORT_NAME_MAP ""
set_interface_property lt24_cs_n CMSIS_SVD_VARIABLES ""
set_interface_property lt24_cs_n SVD_ADDRESS_GROUP ""

add_interface_port lt24_cs_n lt24_cs_n export Output 1


# 
# connection point avalon_master
# 
add_interface avalon_master avalon start
set_interface_property avalon_master addressUnits SYMBOLS
set_interface_property avalon_master associatedClock clock
set_interface_property avalon_master associatedReset reset
set_interface_property avalon_master bitsPerSymbol 8
set_interface_property avalon_master burstOnBurstBoundariesOnly false
set_interface_property avalon_master burstcountUnits WORDS
set_interface_property avalon_master doStreamReads false
set_interface_property avalon_master doStreamWrites false
set_interface_property avalon_master holdTime 0
set_interface_property avalon_master linewrapBursts false
set_interface_property avalon_master maximumPendingReadTransactions 0
set_interface_property avalon_master maximumPendingWriteTransactions 0
set_interface_property avalon_master readLatency 0
set_interface_property avalon_master readWaitTime 1
set_interface_property avalon_master setupTime 0
set_interface_property avalon_master timingUnits Cycles
set_interface_property avalon_master writeWaitTime 0
set_interface_property avalon_master ENABLED true
set_interface_property avalon_master EXPORT_OF ""
set_interface_property avalon_master PORT_NAME_MAP ""
set_interface_property avalon_master CMSIS_SVD_VARIABLES ""
set_interface_property avalon_master SVD_ADDRESS_GROUP ""

add_interface_port avalon_master master_read read Output 1
add_interface_port avalon_master master_readdata readdata Input 32
add_interface_port avalon_master master_address address Output 32
add_interface_port avalon_master master_waitrequest waitrequest Input 1
add_interface_port avalon_master master_readdatavalid readdatavalid Input 1
add_interface_port avalon_master master_burstcount burstcount Output 1
add_interface_port avalon_master master_byteenable byteenable Output 4


# 
# connection point lt24_data
# 
add_interface lt24_data conduit end
set_interface_property lt24_data associatedClock clock
set_interface_property lt24_data associatedReset ""
set_interface_property lt24_data ENABLED true
set_interface_property lt24_data EXPORT_OF ""
set_interface_property lt24_data PORT_NAME_MAP ""
set_interface_property lt24_data CMSIS_SVD_VARIABLES ""
set_interface_property lt24_data SVD_ADDRESS_GROUP ""

add_interface_port lt24_data lt24_data export Output 16


# 
# connection point lt24_lcd_on
# 
add_interface lt24_lcd_on conduit end
set_interface_property lt24_lcd_on associatedClock clock
set_interface_property lt24_lcd_on associatedReset ""
set_interface_property lt24_lcd_on ENABLED true
set_interface_property lt24_lcd_on EXPORT_OF ""
set_interface_property lt24_lcd_on PORT_NAME_MAP ""
set_interface_property lt24_lcd_on CMSIS_SVD_VARIABLES ""
set_interface_property lt24_lcd_on SVD_ADDRESS_GROUP ""

add_interface_port lt24_lcd_on lt24_lcd_on export Output 1


# 
# connection point lt24_rd_n
# 
add_interface lt24_rd_n conduit end
set_interface_property lt24_rd_n associatedClock clock
set_interface_property lt24_rd_n associatedReset ""
set_interface_property lt24_rd_n ENABLED true
set_interface_property lt24_rd_n EXPORT_OF ""
set_interface_property lt24_rd_n PORT_NAME_MAP ""
set_interface_property lt24_rd_n CMSIS_SVD_VARIABLES ""
set_interface_property lt24_rd_n SVD_ADDRESS_GROUP ""

add_interface_port lt24_rd_n lt24_rd_n export Output 1


# 
# connection point lt24_wr_n
# 
add_interface lt24_wr_n conduit end
set_interface_property lt24_wr_n associatedClock clock
set_interface_property lt24_wr_n associatedReset ""
set_interface_property lt24_wr_n ENABLED true
set_interface_property lt24_wr_n EXPORT_OF ""
set_interface_property lt24_wr_n PORT_NAME_MAP ""
set_interface_property lt24_wr_n CMSIS_SVD_VARIABLES ""
set_interface_property lt24_wr_n SVD_ADDRESS_GROUP ""

add_interface_port lt24_wr_n lt24_wr_n export Output 1


# 
# connection point lt24_reset_n
# 
add_interface lt24_reset_n conduit end
set_interface_property lt24_reset_n associatedClock clock
set_interface_property lt24_reset_n associatedReset ""
set_interface_property lt24_reset_n ENABLED true
set_interface_property lt24_reset_n EXPORT_OF ""
set_interface_property lt24_reset_n PORT_NAME_MAP ""
set_interface_property lt24_reset_n CMSIS_SVD_VARIABLES ""
set_interface_property lt24_reset_n SVD_ADDRESS_GROUP ""

add_interface_port lt24_reset_n lt24_reset_n export Output 1


# 
# connection point lt24_rs
# 
add_interface lt24_rs conduit end
set_interface_property lt24_rs associatedClock clock
set_interface_property lt24_rs associatedReset ""
set_interface_property lt24_rs ENABLED true
set_interface_property lt24_rs EXPORT_OF ""
set_interface_property lt24_rs PORT_NAME_MAP ""
set_interface_property lt24_rs CMSIS_SVD_VARIABLES ""
set_interface_property lt24_rs SVD_ADDRESS_GROUP ""

add_interface_port lt24_rs lt24_rs export Output 1

